cinema/cinema/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('films.urls', namespace='films')),
    path('admin_panel/', include('admin_panel.urls', namespace='admin_panel')),
    path('cashier_panel/', include('cashier_panel.urls',
                                   namespace='cashier_panel')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cinema/films/urls.py
from django.urls import path
from . import views

app_name = "films"

urlpatterns = [
    path('', views.FilmListView.as_view(), name='film_list'),
    path('film/<slug:slug>/', views.FilmDetailView.as_view(),
         name='film_detail'),
    path('contacts/', views.ContactsView.as_view(), name='contacts'),
    path('schedule/', views.ScheduleView.as_view(), name='schedule'),
]

cinema/templates/includes/footer.html
<footer class="bg-dark text-light mt-5 py-4">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h5>Кинотеатр</h5>
                <p>Лучшие фильмы в самом центре города.</p>
            </div>
            <div class="col-md-3">
                <h6>Контакты</h6>
                <p>📞 +7 (999) 999-99-99<br>
                📍 г. Томск пр. Комсомольский 13б, ТРЦ «Изумрудный город», 3 этаж.</p>
            </div>
            <div class="col-md-3">
                <h6>Часы работы</h6>
                <p class="mb-0">
                  Ежедневно: 10:00 - 01:00<br>
                  Касса: 10:00 - 23:00
                </p>
            </div>
        </div>
    </div>
</footer>

cinema/templates/includes/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'films:film_list' %}">📽 КИНОТЕАТР</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link {% if request.resolver_match.url_name == 'schedule' %}active active-nav-item{% endif %}" 
                       href="{% url 'films:schedule' %}">Расписание</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.resolver_match.url_name == 'film_list' %}active active-nav-item{% endif %}" 
                       href="{% url 'films:film_list' %}">Афиша</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link {% if request.resolver_match.url_name == 'contacts' %}active active-nav-item{% endif %}" 
                           href="{% url 'films:contacts' %}">О кинотеатре</a>
                </li>
            </ul>
            <form class="d-flex" method="get" action="{% url 'films:film_list' %}">
                <input class="form-control me-2" type="search" name="q" placeholder="Поиск по названию..." 
                       aria-label="Search" value="{{ request.GET.q }}">
                <button class="btn btn-outline-light" type="submit">Найти</button>
            </form>
        </div>
    </div>
</nav>