cinema/admin_panel/urls.py
from django.urls import path
from . import views

app_name = "admin_panel"

urlpatterns = [
    path('', views.AdminRedirectView.as_view(), name='index'),
    path('login/', views.AdminLoginView.as_view(), name='login'),
    path('logout/', views.AdminLogoutView.as_view(), name='logout'),
    path('dashboard/', views.DashboardView.as_view(), name='admin_dashboard'),

    path('films/', views.FilmListView.as_view(), name='film_list'),
    path('films/create/', views.FilmCreateView.as_view(), name='film_create'),
    path('films/update/<int:pk>/',
         views.FilmUpdateView.as_view(), name='film_update'),
    path('films/delete/<int:pk>/',
         views.FilmDeleteView.as_view(), name='film_delete'),

    path('halls/', views.HallListView.as_view(), name='hall_list'),
    path('halls/create/', views.HallCreateView.as_view(), name='hall_create'),
    path('halls/update/<int:pk>/',
         views.HallUpdateView.as_view(), name='hall_update'),
    path('halls/delete/<int:pk>/',
         views.HallDeleteView.as_view(), name='hall_delete'),

    path('sessions/',
         views.SessionScheduleView.as_view(), name='session_schedule'),
    path('sessions/get-times/',
         views.GetTimesView.as_view(), name='get_times'),
    path('sessions/delete/<int:pk>/',
         views.SessionDeleteView.as_view(), name='session_delete'),
]

cinema/cinema/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('films.urls', namespace='films')),
    path('admin_panel/', include('admin_panel.urls', namespace='admin_panel')),
    path('cashier_panel/', include('cashier_panel.urls',
                                   namespace='cashier_panel')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cinema/films/urls.py
from django.urls import path
from . import views

app_name = "films"

urlpatterns = [
    path('', views.FilmListView.as_view(), name='film_list'),
    path('film/<slug:slug>/', views.FilmDetailView.as_view(),
         name='film_detail'),
    path('contacts/', views.ContactsView.as_view(), name='contacts'),
    path('schedule/', views.ScheduleView.as_view(), name='schedule'),
]

cinema/admin_panel/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from datetime import datetime, time, timedelta

User = get_user_model()


class Hall(models.Model):
    number = models.IntegerField('Номер зала', unique=True)
    name = models.CharField('Название зала', max_length=100, default='')
    count_rows = models.IntegerField('Количество рядов', default=10)
    count_places = models.IntegerField('Количество мест в ряду', default=10)
    price = models.IntegerField('Цена билета', default=500)

    class Meta:
        verbose_name = 'зал'
        verbose_name_plural = 'Залы'
        ordering = ('number',)

    def __str__(self):
        return f"{self.number}. {self.name}" if self.name else f"Зал {self.number}"


class Session(models.Model):
    film = models.ForeignKey(
        'films.Film',
        on_delete=models.CASCADE,
        verbose_name='Фильм'
    )
    hall = models.ForeignKey(
        Hall,
        on_delete=models.CASCADE,
        verbose_name='Зал'
    )
    date = models.DateField('Дата сеанса')
    start_time = models.TimeField('Время начала')
    end_time = models.TimeField('Время окончания', blank=True, null=True)

    class Meta:
        verbose_name = 'сеанс'
        verbose_name_plural = 'Сеансы'
        ordering = ('date', 'start_time')
        unique_together = ('hall', 'date', 'start_time')

    def __str__(self):
        return f"{self.film.title} - {self.hall.name} - {self.date} {self.start_time}"

    def clean(self):
        if self.start_time < time(10, 0) or self.start_time > time(23, 0):
            raise ValidationError('Кинотеатр работает с 10:00 до 23:00')

        if self.film.time:
            film_duration = timedelta(
                hours=self.film.time.hour,
                minutes=self.film.time.minute
            )
            start_datetime = datetime.combine(self.date, self.start_time)
            end_datetime = start_datetime + film_duration + timedelta(minutes=30)
            self.end_time = end_datetime.time()

            if end_datetime.time() > time(1, 0) and end_datetime.hour != 0:
                next_day_end = datetime.combine(self.date + timedelta(days=1),
                                                time(1, 0))
                if end_datetime > next_day_end:
                    raise ValidationError('Сеанс должен заканчиваться до 01:00')

        overlapping_sessions = Session.objects.filter(
            hall=self.hall,
            date=self.date
        ).exclude(pk=self.pk)

        for session in overlapping_sessions:
            if (self.start_time < session.end_time and
                    self.end_time > session.start_time):
                raise ValidationError(
                    f'Сеанс пересекается с существующим сеансом: {session}'
                )

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

cinema/films/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Film(models.Model):
    AGE_LIMIT_CHOICES = [
        (0, '0+'),
        (6, '6+'),
        (12, '12+'),
        (16, '16+'),
        (18, '18+'),
    ]

    title = models.CharField('Название', max_length=256)
    description = models.TextField('Описание')
    slug = models.SlugField(
        'Номер фильма',
        unique=True,
        blank=True
    )
    time = models.TimeField('Длительность фильма')
    country = models.CharField('Страна происхождения', max_length=256)
    beginning = models.DateField('Начало показа')
    ending = models.DateField('Конец показа')
    age_limit = models.IntegerField(
        'Возрастное ограничение',
        choices=AGE_LIMIT_CHOICES,
        default=0
    )
    poster = models.ImageField(
        'Афиша',
        upload_to='posters/',
        blank=True,
        null=True
    )

    class Meta:
        verbose_name = 'фильм'
        verbose_name_plural = 'Фильмы'
        ordering = ('title',)

    def save(self, *args, **kwargs):
        if not self.slug:
            count = Film.objects.count()
            base_slug = str(count + 1)
            self.slug = base_slug
            original_slug = self.slug
            counter = 1
            while Film.objects.filter(slug=self.slug).exclude(pk=self.pk).exists():
                self.slug = f"{original_slug}-{counter}"
                counter += 1

        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

cinema/admin_panel/views.py
from .models import Hall, Session
from films.models import Film
from .forms import FilmForm, HallForm, SessionForm
from django.views.generic import (ListView, CreateView, UpdateView,
                                  DeleteView, TemplateView, View, FormView)
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.utils import timezone
from datetime import datetime, time, timedelta


class AdminRequiredMixin(LoginRequiredMixin, UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_staff


class AdminRedirectView(View):
    def get(self, request):
        if request.user.is_authenticated and request.user.is_staff:
            return redirect('admin_panel:admin_dashboard')
        return redirect('admin_panel:login')


class AdminLoginView(View):
    def get(self, request):
        return render(request, 'admin_panel/login.html')

    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None and user.is_staff:
            login(request, user)
            return redirect('admin_panel:admin_dashboard')
        return render(request, 'admin_panel/login.html')


class AdminLogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('admin_panel:login')


class DashboardView(AdminRequiredMixin, TemplateView):
    template_name = 'admin_panel/admin_dashboard.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['stats'] = {
            'films_count': Film.objects.count(),
            'halls_count': Hall.objects.count(),
            'sessions_today': Session.objects.filter(date=timezone.now().date()).count(),
            'active_films': Film.objects.filter(ending__gte=timezone.now().date()).count()
        }
        context['film_list'] = Film.objects.all()[:5]
        return context


class FilmListView(AdminRequiredMixin, ListView):
    model = Film
    template_name = 'admin_panel/film_list.html'
    context_object_name = 'films'

    def get_queryset(self):
        return Film.objects.all().order_by('-ending', 'title')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        today = timezone.now().date()

        active_films = []
        archive_films = []

        for film in context['films']:
            if film.ending >= today:
                active_films.append(film)
            else:
                archive_films.append(film)

        context['active_films'] = active_films
        context['archive_films'] = archive_films
        context['today'] = today

        return context


class FilmCreateView(AdminRequiredMixin, CreateView):
    model = Film
    form_class = FilmForm
    template_name = 'admin_panel/film_form.html'
    success_url = reverse_lazy('admin_panel:film_list')


class FilmUpdateView(AdminRequiredMixin, UpdateView):
    model = Film
    form_class = FilmForm
    template_name = 'admin_panel/film_form.html'
    success_url = reverse_lazy('admin_panel:film_list')


class FilmDeleteView(AdminRequiredMixin, DeleteView):
    model = Film
    template_name = 'admin_panel/confirm_delete.html'
    success_url = reverse_lazy('admin_panel:film_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['back_url'] = 'admin_panel:film_list'
        return context


class HallListView(AdminRequiredMixin, ListView):
    model = Hall
    template_name = 'admin_panel/hall_list.html'
    context_object_name = 'halls'


class HallCreateView(AdminRequiredMixin, CreateView):
    model = Hall
    form_class = HallForm
    template_name = 'admin_panel/hall_create.html'
    success_url = reverse_lazy('admin_panel:hall_list')


class HallUpdateView(AdminRequiredMixin, UpdateView):
    model = Hall
    form_class = HallForm
    template_name = 'admin_panel/hall_edit.html'
    success_url = reverse_lazy('admin_panel:hall_list')


class HallDeleteView(AdminRequiredMixin, DeleteView):
    model = Hall
    template_name = 'admin_panel/confirm_delete.html'
    success_url = reverse_lazy('admin_panel:hall_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['back_url'] = 'admin_panel:hall_list'
        return context


class SessionScheduleView(AdminRequiredMixin, FormView):
    template_name = 'admin_panel/session_schedule.html'
    form_class = SessionForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'halls': Hall.objects.all(),
            'films': Film.objects.filter(ending__gte=timezone.now().date()),
            'sessions': Session.objects.filter(
                date__range=[timezone.now().date(), timezone.now().date() + timedelta(days=14)]
            ),
            'today': timezone.now().date()
        })

        film_id = self.request.GET.get('film_id')
        hall_id = self.request.GET.get('hall_id')
        date = self.request.GET.get('date')

        if film_id and hall_id and date:
            context.update({
                'selected_film': Film.objects.get(pk=film_id),
                'selected_hall': Hall.objects.get(pk=hall_id),
                'selected_date': datetime.strptime(date, '%Y-%m-%d').date(),
                'available_times': GetTimesView().get_times(
                    Film.objects.get(pk=film_id),
                    Hall.objects.get(pk=hall_id),
                    datetime.strptime(date, '%Y-%m-%d').date()
                )
            })
        return context

    def form_valid(self, form):
        form.save()
        return redirect('admin_panel:session_schedule')


class GetTimesView(AdminRequiredMixin, View):
    def get(self, request):
        hall_id = request.GET.get('hall_id')
        date = request.GET.get('date')
        film_id = request.GET.get('film_id')

        if not all([hall_id, date, film_id]):
            return JsonResponse({'times': []})

        hall = Hall.objects.get(pk=hall_id)
        film = Film.objects.get(pk=film_id)
        selected_date = datetime.strptime(date, '%Y-%m-%d').date()
        times = self.get_times(film, hall, selected_date)
        return JsonResponse({'times': times})

    def get_times(self, film, hall, selected_date):
        existing_sessions = Session.objects.filter(hall=hall,
                                                   date=selected_date)
        times = []
        current_time = time(10, 0)

        while current_time <= time(22, 0):
            film_minutes = film.time.hour * 60 + film.time.minute
            current_minutes = current_time.hour * 60 + current_time.minute
            end_minutes = current_minutes + film_minutes
            proposed_end = time(end_minutes // 60, end_minutes % 60)

            if proposed_end > time(23, 0):
                break

            conflict = any(
                current_time < session.end_time and proposed_end > session.start_time
                for session in existing_sessions
            )

            if not conflict:
                times.append(current_time.strftime('%H:%M'))

            next_minutes = end_minutes + 30
            if next_minutes >= 23 * 60:
                break
            current_time = time(next_minutes // 60, next_minutes % 60)

        return times


class SessionDeleteView(AdminRequiredMixin, DeleteView):
    model = Session
    template_name = 'admin_panel/confirm_delete.html'
    success_url = reverse_lazy('admin_panel:session_schedule')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['back_url'] = 'admin_panel:session_schedule'
        return context

cinema/films/views.py
from .models import Film
from admin_panel.models import Session
from django.views.generic import ListView, DetailView, TemplateView
from django.utils import timezone
from datetime import timedelta


class FilmListView(ListView):
    model = Film
    template_name = 'films/film_list.html'
    context_object_name = 'films'

    def get_queryset(self):
        today = timezone.now().date()
        queryset = Film.objects.filter(ending__gte=today).order_by('title')

        query = self.request.GET.get('q', '').strip()
        if query:
            queryset = queryset.filter(title__iregex=query)

        return queryset


class FilmDetailView(DetailView):
    model = Film
    template_name = 'films/film_detail.html'
    context_object_name = 'film'
    slug_field = 'slug'
    slug_url_kwarg = 'slug'


class ContactsView(TemplateView):
    template_name = 'films/contacts.html'


class ScheduleView(TemplateView):
    template_name = 'films/schedule.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        start_date = timezone.now().date()
        end_date = start_date + timedelta(days=13)
        sessions = Session.objects.filter(
            date__range=[start_date, end_date]
        ).select_related('film', 'hall').order_by('date', 'start_time')

        sessions_by_date = {}
        for session in sessions:
            date_str = session.date.strftime('%Y-%m-%d')
            if date_str not in sessions_by_date:
                sessions_by_date[date_str] = []
            sessions_by_date[date_str].append(session)

        dates = []
        for i in range(14):
            current_date = start_date + timedelta(days=i)
            dates.append({
                'date': current_date,
                'sessions': sessions_by_date.get(
                    current_date.strftime('%Y-%m-%d'), [])
            })

        context.update({
            'dates': dates,
            'today': start_date
        })

        return context

cinema/templates/admin_panel/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Панель администратора{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css">
</head>
<body>
    <style>
        .sidebar {
            min-height: 100vh;
            background-color: #343a40;
        }
        .sidebar .nav-link {
            color: #fff;
            padding: 0.75rem 1rem;
            border-radius: 0.25rem;
            margin: 0.125rem 0;
        }
        .sidebar .nav-link:hover {
            background-color: #495057;
        }
        .sidebar .nav-link.active {
            background-color: #0d6efd;
        }
    </style>    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'admin_panel:admin_dashboard' %}">Панель администратора</a>
            <div class="d-flex">
                <span class="navbar-text me-3">
                    Добро пожаловать, {{ user.username }}
                </span>
                <a href="{% url 'admin_panel:logout' %}" class="btn btn-outline-light">Выйти</a>
            </div>
        </div>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3 col-lg-2 sidebar">
                <nav class="nav flex-column p-3">
                    <a class="nav-link {% if request.resolver_match.url_name == 'admin_dashboard' %}active{% endif %}" 
                       href="{% url 'admin_panel:admin_dashboard' %}">Панель администратора</a>
                    
                    <li class="nav-item text-light fw-bold mt-3 mb-2">Управление фильмами</li>
                    <a class="nav-link {% if 'film' in request.resolver_match.url_name %}active{% endif %}" 
                       href="{% url 'admin_panel:film_list' %}">Все фильмы</a>
                    <a class="nav-link" href="{% url 'admin_panel:film_create' %}">Добавить фильм</a>
                    
                    <li class="nav-item text-light fw-bold mt-3 mb-2">Управление залами</li>
                    <a class="nav-link {% if 'hall' in request.resolver_match.url_name %}active{% endif %}" 
                       href="{% url 'admin_panel:hall_list' %}">Все залы</a>
                    <a class="nav-link" href="{% url 'admin_panel:hall_create' %}">Добавить зал</a>
                    
                    <li class="nav-item text-light fw-bold mt-3 mb-2">Расписание</li>
                    <a class="nav-link {% if 'session' in request.resolver_match.url_name %}active{% endif %}" 
                       href="{% url 'admin_panel:session_schedule' %}">Сеансы</a>
                </nav>
            </div>

            <main class="col-md-9 col-lg-10 px-4 py-3">
                {% if messages %}
                <div class="messages">
                    {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                    </div>
                    {% endfor %}
                </div>
                {% endif %}

                <div class="d-flex justify-content-between align-items-center mb-4">
                    <h2 class="h3 mb-0">{% block page_title %}{% endblock %}</h2>
                    {% block button %}{% endblock %}
                </div>

                {% block content %}
                {% endblock %}
            </main>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    {% block extra_js %}{% endblock %}
</body>
</html>

cinema/templates/admin_panel/confirm_delete.html
{% extends 'admin_panel/base.html' %}

{% block title %}Подтверждение удаления{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card shadow">
            <div class="card-header bg-danger text-white">
                <h5 class="mb-0">Подтверждение удаления</h5>
            </div>
            <div class="card-body text-center">
                <form method="post" class="mt-4">
                    {% csrf_token %}
                    <div class="d-grid gap-2 d-md-flex justify-content-md-center">
                        <button type="submit" class="btn btn-danger">Да, удалить</button>
                        <a href="{% url back_url %}" class="btn btn-secondary">Отмена</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

cinema/templates/admin_panel/film_list.html
{% extends 'admin_panel/base.html' %}
{% load static %}

{% block title %}Фильмы{% endblock %}
{% block page_title %}Управление фильмами{% endblock %}

{% block button %}
<a href="{% url 'admin_panel:film_create' %}" class="btn btn-primary">Добавить фильм</a>
{% endblock %}

{% block content %}
<div class="card shadow">
    <div class="card-body">
        {% if active_films or archive_films %}
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Постер</th>
                        <th>Название</th>
                        <th>Длительность</th>
                        <th>Период показа</th>
                        <th>Статус</th>
                        <th>Действия</th>
                    </tr>
                </thead>
                <tbody>
                    {% for film in active_films %}
                    <tr>
                        <td>
                            {% if film.poster %}
                                <img src="{{ film.poster.url }}" alt="{{ film.title }}" 
                                     class="rounded" width="50" height="70" style="object-fit: cover;">
                            {% else %}
                                <img src="{% static 'images/poster_none.png' %}" alt="{{ film.title }}" 
                                     class="rounded" width="50" height="70" style="object-fit: cover;">
                            {% endif %}
                        </td>
                        <td>
                            <strong>{{ film.title }}</strong><br>
                            <small class="text-muted">{{ film.country }}</small>
                        </td>
                        <td>{{ film.time|time:"H:i" }}</td>
                        <td>
                            {{ film.beginning|date:"d.m.Y" }}<br>
                            <small class="text-muted">по {{ film.ending|date:"d.m.Y" }}</small>
                        </td>
                        <td>
                            <span class="badge bg-success">Активный</span><br>
                            <span class="badge bg-secondary">{{ film.get_age_limit_display }}</span>
                        </td>
                        <td>
                            <div class="btn-group btn-group-sm">
                                <a href="{% url 'admin_panel:film_update' film.pk %}" 
                                   class="btn btn-outline-primary" title="Редактировать">
                                    <i class="bi bi-pencil"></i>
                                </a>
                                <a href="{% url 'admin_panel:film_delete' film.pk %}" 
                                   class="btn btn-outline-danger" title="Удалить">
                                    <i class="bi bi-trash"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}

                    {% if archive_films %}
                    <tr class="bg-light">
                        <td colspan="6" class="text-center py-3">
                            <h5 class="text-muted mb-0">Архив</h5>
                        </td>
                    </tr>
                    {% endif %}

                    {% for film in archive_films %}
                    <tr class="text-muted">
                        <td>
                            {% if film.poster %}
                                <img src="{{ film.poster.url }}" alt="{{ film.title }}" 
                                     class="rounded" width="50" height="70" style="object-fit: cover; opacity: 0.6;">
                            {% else %}
                                <img src="{% static 'images/poster_none.png' %}" alt="{{ film.title }}" 
                                     class="rounded" width="50" height="70" style="object-fit: cover; opacity: 0.6;">
                            {% endif %}
                        </td>
                        <td>
                            <strong>{{ film.title }}</strong><br>
                            <small class="text-muted">{{ film.country }}</small>
                        </td>
                        <td>{{ film.time|time:"H:i" }}</td>
                        <td>
                            {{ film.beginning|date:"d.m.Y" }}<br>
                            <small class="text-muted">по {{ film.ending|date:"d.m.Y" }}</small>
                        </td>
                        <td>
                            <span class="badge bg-secondary">Архив</span><br>
                            <span class="badge bg-light text-dark">{{ film.get_age_limit_display }}</span>
                        </td>
                        <td>
                            <div class="btn-group btn-group-sm">
                                <a href="{% url 'admin_panel:film_update' film.pk %}" 
                                   class="btn btn-outline-secondary" title="Редактировать">
                                    <i class="bi bi-pencil"></i>
                                </a>
                                <a href="{% url 'admin_panel:film_delete' film.pk %}" 
                                   class="btn btn-outline-danger" title="Удалить">
                                    <i class="bi bi-trash"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
        <div class="text-center py-5">
            <i class="bi bi-film display-1 text-muted"></i>
            <h4 class="text-muted mt-3">Фильмы не найдены</h4>
            <p class="text-muted">Добавьте первый фильм в систему</p>
            <a href="{% url 'admin_panel:film_create' %}" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> Добавить фильм
            </a>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

cinema/templates/admin_panel/hall_create.html
{% extends 'admin_panel/base.html' %}

{% block title %}Создать новый зал{% endblock %}
{% block page_title %}Создать новый зал{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-lg-8">
        <div class="card border-0 shadow">
            <div class="card-body p-4">
                <form method="post">
                    {% csrf_token %}

                    <div class="mb-4">
                        <label class="form-label fw-semibold">Название зала</label>
                        <input type="text" name="name" class="form-control" required id="id_name">
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label class="form-label fw-semibold">Номер зала</label>
                                <input type="number" name="number" class="form-control" required id="id_number">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label class="form-label fw-semibold">Цена билета</label>
                                <div class="input-group">
                                    <input type="number" name="price" value="500" class="form-control" required id="id_price">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label class="form-label fw-semibold">Количество рядов</label>
                                <input type="number" name="count_rows" value="10" class="form-control" required id="id_count_rows">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label class="form-label fw-semibold">Количество мест в ряду</label>
                                <input type="number" name="count_places" value="10" class="form-control" required id="id_count_places">
                            </div>
                        </div>
                    </div>

                    <div class="d-flex justify-content-between mt-4 pt-3">
                        <a href="{% url 'admin_panel:hall_list' %}" class="btn btn-outline-secondary">Назад к списку</a>
                        <button type="submit" class="btn btn-primary px-4">Сохранить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}